In [2]:
import dgl

import torch





In [3]:
src = torch.tensor([0, 1, 0, 1], dtype=torch.int64)
dst = torch.tensor([1, 0, 2, 2], dtype=torch.int64)

features = torch.tensor([
    [1, 1],
    [2, 1],
    [1, 2]
], dtype=torch.float32)


graph = dgl.graph((src, dst))
graph

Graph(num_nodes=3, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

In [27]:
in_degrees = graph.in_degrees()
out_degrees = graph.out_degrees()


in_degrees, out_degrees

(tensor([1, 1, 2]), tensor([2, 2, 0]))

In [28]:
graph.adj().to_dense()

tensor([[0., 1., 1.],
        [1., 0., 1.],
        [0., 0., 0.]])

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 0.5000]])

In [34]:
graph.adj().to_dense() / in_degrees.unsqueeze(1)

tensor([[0., 1., 1.],
        [1., 0., 1.],
        [0., 0., 0.]])

In [40]:
torch.diag(1 / in_degrees) @ graph.adj().to_dense().T @ features

tensor([[2.0000, 1.0000],
        [1.0000, 1.0000],
        [1.5000, 1.0000]])

In [4]:
dgl.ops.copy_u_mean(graph, features)

tensor([[2.0000, 1.0000],
        [1.0000, 1.0000],
        [1.5000, 1.0000]])

In [13]:
conv = dgl.nn.pytorch.GraphConv(weight=False, bias=False, in_feats=2, out_feats=2, norm='both')

In [14]:
conv(graph, features)

tensor([[1.4142, 0.7071],
        [0.7071, 0.7071],
        [1.5000, 1.0000]])